name: Build

on: [push]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install ruby dependencies
        run: bundle install
      - name: Build
        run: bundle exec jekyll build
