name: QA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1'

jobs:
  build:
    name: QA Job
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install ruby dependencies
        run: bundle install
      - name: Build
        run: bundle exec jekyll build
      - name: QA
        run: bundle exec htmlproofer --check-html _site

